version: '3.9'

name: piggery-docker

services:
  automatic:
    extends: 
      file: ./stable-diffusion-webui-docker/docker-compose.yml
      service: auto
    environment:
      - COMPOSE_PROFILES=auto
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api --cors-allow-origins=* --listen
